src/Elements/Bundle/ProcessManagerBundle/Helper.php

If there are montitoring items which have a logger class configured which cannot be resolved (any more) the processmanger-maintenance command will fail and therefore the montioring item cleanup won't be performed.

Skip not existing configured logger classes

---

src/Elements/Bundle/ProcessManagerBundle/Model/MonitoringItem.php

As all other setters of Elements\Bundle\ProcessManagerBundle\Model\MonitoringItem are fluid, so should setModificationDate() and setCreationDate() are. While this is not absolutely necessary for setCreationDate() because it gets called on initialisation internally, it is quite handy for setModificationDate() because this needs to be called by the called command - otherwise the `duration` field in the status table is always "-".

Fluid setters

---

src/ExecutionTrait.php

Otherwise the maintenance command of the process manager fails with a system error.

Check if file exists before fileowner()

---

src/Migrations/Version00000004.php

We shouldn't drop a column that doesn't exist.

Fix condition, so migrations don't die

---

src/Resources/public/js/executor/class/abstractExecutor.js

As http://cron.nmonitoring.com/cron-generator.html is not available anymore this PR changes the link for creating the cronjob frequency setting to https://crontab.guru

Change link to crontab generator

---

src/ExecutionTrait.php

When executing a command which uses the `ExecutionTrait` via code the constant `PIMCORE_CONSOLE` is not set. This results in `Warning: Use of undefined constant PIMCORE_CONSOLE - assumed 'PIMCORE_CONSOLE' (this will throw an Error in a future version of PHP)`

Check for existence of PIMCORE_CONSOLE constant

---

src/Model/MonitoringItem.php

In some cases, as there are several loggers, it could be nice to set the default message log level. It is thus possible to filter its display according to each the logger.

Add LogLevel options to setDefaultProcessMessage method

---

src/Installer.php
src/Resources/translations/admin.en.csv

Symfony looks at `<bundle dir>/Resources/translations/<domain>.<locale>.yml` by default for translations. For Pimcore backend translations the domain is `admin`. This way we do not need to import anything during installation but it just works out of the box.
And it has the additional advantage that translations fall back to `en` if no translations for desired language exist. Before this PR you only see the translation keys when you switch the account language of the current Pimcore user to anything else than `en`:

Use symfony standard for translations

---

src/Migrations/Version00000022.php

Currently the columns `plugin_process_manager_monitoring_item.currentStep` and `totalSteps` are of type `unsigned tinyint` meaning that a maximum of 255 steps is supported. When you for example have a file upload you could easily excess this limit. This PR changes the column types to `unsigned smallint` allowing a maximum of 65535 steps.

Allow more than 255 steps

---

src/Migrations/Version00000019.php
src/Migrations/Version00000020.php
src/Migrations/Version00000021.php

Resolves #79
I did not remove `Version00000019.php` because otherwise on those systems where this translation already has been executed a message would appear stating that you have executed a migration which is not available.

Remove Installer::updateTranslations() which does not exist anymore

---

src/ExecutionTrait.php
src/Helper.php

MonitoringItem::getMetaData() is supposed to return string, but in this particular case it doesn't:
```php
$this->executeChildProcesses($parentItem, $jobs, 3, 50,
function (MonitoringItem $childItem, PimcoreCommand $executor) use ($sourceName) {
$metadata = $child->getMetaData();  // Should be string, but is actually array
// ...
}
);
```
This is a small fix for that case.

Fix metaData data type

---

src/ExecutionTrait.php
src/Model/MonitoringItem.php

This replaces #87 and #88. It makes #87 obsolete, and integrates #88 as a separate commit (0a05b32745926c2266c6ff1a094685e292452f91) to make it easier to merge.

Fix test for failed child processes + More detailed progress for parallel imports

---

src/Controller/ConfigController.php

Copied code from MonitoringItemController, but I didn't do `array_merge($request->request->all(), $request->query->all())`, since it seems like parameters are always passed as POST request data.

Fix sort for process list

---

src/ElementsProcessManagerBundle.php

With Pimcore versione 10.x they added this line on code 
https://github.com/pimcore/pimcore/blob/3ff186d50b7baf53ec29ebe2b516a660f6700fb2/lib/Extension/Bundle/Traits/PackageVersionTrait.php#L35
That generate an error here
https://github.com/elements-at/ProcessManager/blob/4a0715b0d9e7777a8a18345d331bc95d31276bce/src/ElementsProcessManagerBundle.php#L233
Pull request fixes that

Added return specification

---

src/Model/Configuration.php

Sorry, bad commit description, fix in PR description
With PHP8, a number of notices have been converted into warnings, like attempting to read an undefined array key.
```php
ErrorException {#2016
#message: "Warning: Undefined array key 1"
#code: 0
#file: "./vendor/elements/process-manager-bundle/src/Model/Configuration.php"
#line: 365
#severity: E_WARNING
trace: {
./vendor/elements/process-manager-bundle/src/Model/Configuration.php:365 { …}
./src/ExtendProcessManagerBundle/Model/Configuration.php:14 {
App\ExtendProcessManagerBundle\Model\Configuration::createOrUpdateFromValues(array $configurationValues)
```
This PR fix it

PHP8 - Fix PHP Warning attempting to read an undefined array key.

---

src/Model/MonitoringItem.php

Fix Fatal Error on Pimcore X. 
Function \Pimcore\Tool\Console::exec  has been removed

Pimcore X : \Pimcore\Tool\Console::exec doesn't exist

---

src/Service/CommandsValidator.php

When using PHP8 attributes to declare a command, Symfony Command Application `registerCommands` returns `LazyCommand` class.
The `classUsesTraits` function does not detect `ExecutionTrait::class` in the command.
To reproduce
Actually, this command is avaible in process manager
```php
<?php
namespace App\Command;
use Elements\Bundle\ProcessManagerBundle\ExecutionTrait;
use Pimcore\Console\AbstractCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
class Demo extends AbstractCommand
{
use ExecutionTrait;
public function configure()
{
$this->setName('app:demo');
}
public function execute(InputInterface $input, OutputInterface $output)
{
$output->writeln('Simple Demo - Do Noting');
return self::SUCCESS;
}
}
```
This, not
```php …
```

Add Support for LazyLoad Commands

---

doc/migration.md

[Docs] Line break in Markdown file does not cause line break in output

---

src/Maintenance.php

Fix an error for when "defaultPreDefinedConfig" is not set in the ExecutorSettings.

Fix undefined array key - Exception in Maintenance

---

src/Maintenance.php

The check prevents an error situation in the getById call. If no predefined settings are set in the Pimcore backend, the value of 'defaultPreDefinedConfig' is an empty string.

Check if defaultPreDefinedConfig is of type integer

---

doc/actions.md
doc/usageParallelization.md

I found a broken link in the parallelization documentation and fixed that one. In addition I also added a hint in the Actions document to describe the optional property ExecuteAtStates

Documentation update (link correction, feature description)

---

src/Controller/CallbackSettingsController.php
src/ExecutionTrait.php
src/Resources/public/css/admin.css

- Removes use of `json_encode` when executing child processes to match `setMetadata` function parameter type
- Fixes bug where an exception was thrown when loading a predefined config, which meant the predefined config could not be loaded at all
- Adds background colours back to process list

Remove json encode for child process metadata

---

src/Command/MigrationGeneratorCommand.php

Fixes deprecation warning:
*Method "Symfony\Component\Console\Command\Command::configure()" might add "void" as a native return type declaration in the future. Do the same in child class "Elements\Bundle\ProcessManagerBundle\Command\MigrationGeneratorCommand" now to avoid errors or add an explicit @return annotation to suppress this message.*

Add void return-type to MigrationGeneratorCommand::configure()

---

composer.json

Resolves #208 
1. Config
2. Process Log
3. Crontab excecution
4. Adding custom action button via JS Event
5. Email Logger
https://www.php.net/manual/en/migration83.incompatible.php
> #### Uses of traits with static properties
> Uses of traits with static properties will now redeclare static properties inherited from the parent class. This will create a separate static property storage for the current class. This is analogous to adding the static property to the class directly without traits.
`ExecutionTrait` has some static properties, they are only accessed via `static::$propName` calls so this shouldn't have any notable change.
> The DateTime extension has introduced Date extension specific exceptions and errors under the [DateError](https://www.php.net/manual/en/class.dateerror.php) …

Add PHP 8.3 support

---

src/Model/MonitoringItem.php

Fixes failing child processes due to [this change](https://github.com/pimcore/pimcore/pull/16742) in the pimcore repository

Use setOrderKey instead of setOrder

---

src/Model/MonitoringItem.php

Fixes error:
```
In MonitoringItem.php line 398:
Elements\Bundle\ProcessManagerBundle\Model\MonitoringItem::setMessage(): Argument #1 ($message) must be of type string, null given, called in /var/www/pimcore/vendor/elements/process-manager-bundle/src/Model/MonitoringItem.php on line 285
```

Update MonitoringItem to make sure to send strings where required

---

src/Model/Configuration/Listing/Dao.php

Fix issue #207 by ensuring the correct data is set in the Configuration/Listing/Dao::load() method. 
This fix ensures the $listing->current() method used in RestController::ExecuteAction() operates correctly.

Fix Configuration\Listing\Dao::load() - Exception in RestController::ExecuteAction()

---

doc/configuration.md

Either double backspace and double quotes, or single quotes.
`  #message: "The file "/app/config/packages/elements_process_manager.yaml" does not contain valid YAML: Found unknown escape character "\M" at line 11 (near "configurationMigrationsNamespace: "App\Migrations"") in /app/config/packages/elements_process_manager.yaml (which is being imported from "/app/src/Kernel.php")."`

Single quote namespace containing single backspace
